// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
export const CONTRACT_VERSION = "1.0.0" as const;
export const CONTRACT_TREE_SHA256 = "c012efb7dc8ae98232b0efd70b9a495cd057ea3f33c1841543674a030dd129c0" as const;
export const WS_MESSAGE_TYPES = ["command.ack", "operations.event", "order.command", "report.ack", "robot.event.report", "robot.state.report", "stream.welcome"] as const;
export type WsMessageType = (typeof WS_MESSAGE_TYPES)[number];
export const POLICY_INPUT_NAMES = ["grid", "goal", "neighbors", "neighborMask"] as const;
export const GRID_CHANNELS = ["staticBlocked", "dynamicOccupied", "foreignReserved", "routeAllowed"] as const;
export const NEIGHBOR_FEATURES = ["deltaXMeters", "deltaYMeters", "velocityXMps", "velocityYMps", "radiusMeters", "stateAgeSeconds"] as const;
export const ACTION_CANDIDATES = ["WAIT", "NORTH", "EAST", "SOUTH", "WEST"] as const;
export type ActionCandidate = (typeof ACTION_CANDIDATES)[number];

export interface WsEnvelope<TPayload extends object = Record<string, unknown>> {
  contractVersion: typeof CONTRACT_VERSION;
  messageId: string;
  messageType: WsMessageType;
  producer: { kind: "CORE" | "SIMULATOR"; id: string };
  occurredAt: string;
  correlationId: string;
  payload: TPayload;
}

export interface SimulatorReportIdentity {
  sessionEpoch: number;
  simulatorId: string;
  simulatorBootId: string;
  reportSequence: number;
  robotId: string;
}

export interface ReportAckPayload {
  reportMessageId: string;
  simulatorBootId: string;
  reportSequence: number;
  disposition: "ACCEPTED" | "DUPLICATE" | "REJECTED";
  durability: "DURABLE" | "PROJECTION";
  retryable: boolean;
  code: string;
}
