// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
export interface LocalMapActivation {
  contractVersion: "1.0.0";
  requestId: string;
  mapId: string;
  generation: number;
}

export interface LocalMapOption {
  mapId: string;
  mapType: "standard" | "mega";
}

export interface LocalMapRuntimeAck {
  contractVersion: "1.0.0";
  role: "simulator" | "planner" | "retention";
  generation: number;
  bootId: string;
  state: "STOPPED" | "READY";
}

export interface LocalMapRuntimeState {
  contractVersion: "1.0.0";
  generation: number;
  phase: "ACTIVE" | "STOPPING" | "RESETTING" | "PREPARING" | "FAILED";
  requestId: string | null;
  activeMapId: string;
  targetMapId: string;
  error: string | null;
  maps: LocalMapOption[];
  bootId: string;
  mapType: "standard" | "mega";
  fleetReady: boolean;
}

export interface LocalMapState {
  contractVersion: "1.0.0";
  generation: number;
  phase: "ACTIVE" | "STOPPING" | "RESETTING" | "PREPARING" | "FAILED";
  requestId: string | null;
  activeMapId: string;
  targetMapId: string;
  error: string | null;
  maps: LocalMapOption[];
}
