// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
export interface AcknowledgeMotionProfilesRequest {
  contractVersion: "1.0.0";
  requestId: string;
  bootId: string;
  targets: MotionProfileTarget[];
}

export interface CreateRobotRequest {
  contractVersion: "1.0.0";
  requestId: string;
  map: ProvisioningMap;
  start: StartCell;
}

export interface MotionProfile {
  robotId: string;
  version: number;
  appliedVersion: number;
  limits: MotionProfileLimits;
}

export interface MotionProfileLimits {
  maxLinearSpeedMps: number;
  maxLinearAccelerationMps2: number;
  maxLinearDecelerationMps2: number;
  maxLinearJerkMps3: number;
}

export interface MotionProfileTarget {
  robotId: string;
  version: number;
}

export interface MotionProfilesOutcome {
  contractVersion: "1.0.0";
  profiles: MotionProfile[];
}

export interface MotionRoutePlan {
  contractVersion: "1.0.0";
  profileVersion: number;
  limits: MotionProfileLimits;
  segments: MotionRouteSegment[];
}

export interface MotionRouteSegment {
  startColumn: number;
  startRow: number;
  endColumn: number;
  endRow: number;
  startSimulationTimeMs: number;
  endSimulationTimeMs: number;
}

export interface ProvisioningCapabilities {
  contractVersion: "1.0.0";
  available: boolean;
}

export interface ProvisioningMap {
  mapId: string;
  revision: number;
  contentDigestSha256: string;
}

export interface ProvisioningOutcome {
  contractVersion: "1.0.0";
  robotId: string;
  state: "PENDING" | "STARTING" | "READY" | "FAILED";
  failureCode?: string | null;
}

export interface RemoveRobotRequest {
  contractVersion: "1.0.0";
  requestId: string;
}

export interface RetryRobotRequest {
  contractVersion: "1.0.0";
  requestId: string;
}

export interface RobotRemovalOutcome {
  contractVersion: "1.0.0";
  robotId: string;
  state: "PENDING" | "REMOVED";
}

export interface RuntimeClaimOutcome {
  contractVersion: "1.0.0";
  robots: RuntimeRobotClaim[];
}

export interface RuntimeClaimRequest {
  contractVersion: "1.0.0";
  bootId: string;
  runningRobotIds: string[];
}

export interface RuntimeRemovalOutcome {
  contractVersion: "1.0.0";
  removals: RobotRemovalOutcome[];
}

export interface RuntimeRemovalRequest {
  contractVersion: "1.0.0";
  bootId: string;
}

export interface RuntimeResultRequest {
  contractVersion: "1.0.0";
  bootId: string;
  leaseEpoch: number;
  failureCode: "UNSAFE_START" | "START_FAILED" | "CHECKPOINT_INVALID";
}

export interface RuntimeRobotClaim {
  robotId: string;
  simulatorId: string;
  apiKey: string;
  leaseEpoch: number;
  map: ProvisioningMap;
  start: StartCell;
}

export interface SetMotionProfilesRequest {
  contractVersion: "1.0.0";
  requestId: string;
  targets: MotionProfileTarget[];
  limits: MotionProfileLimits;
}

export interface StartCell {
  column: number;
  row: number;
}

export interface TrafficWait {
  contractVersion: "1.0.0";
  reason: "PASSAGE_RIGHT_UNAVAILABLE";
  blockingRobotIds: string[];
}
